#! /bin/env Rscript


###################################################
de_tip_no <- function(tip){
	names <- unlist(strsplit(tip, "[|]"))
	#names <- unlist(apply(names, sub, '^[0-9]+_', ''))
	names <- sub('^[0-9]+_', '', names)
	tip.new <- paste(names, collapse='|')
	return(tip.new)
}


de_tip_no_for_tree <- function(t){
	t$tip.label <- unlist(lapply(t$tip.label, de_tip_no))
	return(t)
}


###################################################
get_node_to_two_taxon_name <- function(t, is_de_tip_no=F){
	library(phangorn)
	suppressMessages(library(phytools))
	suppressMessages(library(phylobase))

	node_to_two_taxon_name <- vector()
	t.pb <- phylo4(t) # phylobase
	n_tips <- length(t$tip.label)
	n_all_nodes <- t$Nnode + length(t$tip.label)
	for(i in (n_tips+1):n_all_nodes){
		children <- children(t.pb, i)
		tips <- NULL
		for(child in children){
			tip_node <- unlist(Descendants(t, child, type = c("tips")))[1]
			tip <- t$tip.label[tip_node] # could be 6_Homo_sapiens
			if(is_de_tip_no){tip <- de_tip_no(tip)}
			tips <- append(tips, tip)
			#tips <- append(tips, t$tip.label[tip_node])
		}
		# note that here internal node index starts from 1, which differs from the default in ape
		node_to_two_taxon_name[i-n_tips] <- paste(tips, collapse="|")
	}
	return(node_to_two_taxon_name)
}


###################################################
# read mncmc.txt generated by MCMCTree
get_mcmc_obj <- function(infile, n=-1){
	library(coda)
	t <- read.table(infile, header=TRUE, nrows=n)
	t <- t[, -which(colnames(t) %in% c('Gen'))]
	m <- mcmc(t)
}


