#! /bin/env Rscript


###########################################
# read the tree in the file 'out' generated by MCMCTree (the line following the SENTENCE; see below)


###########################################
suppressMessages(library(phytools))


###########################################
SENTENCE <- 'Species tree for FigTree'
line_no <- 0


###########################################
grep_sentence <- function(line){
	line_no <<- line_no + 1
	if(grepl(SENTENCE, line)){
		return(line_no)
	}else{
		return(F)
	}
}


###########################################
read_ont <- function(mcmc_out_file){
	line_no <- 0

	in_fh = file(mcmc_out_file, "r")

	lines <- readLines(in_fh)

	close(in_fh)

	got_line_nos <- unlist(lapply(lines, grep_sentence)) # 0 for F (not matched)

	final_lines <- lines[which(got_line_nos > 0) + 1]

	if(length(final_lines) >= 1){
		return(read.tree(text=final_lines[1]))
	}else{
		stop(paste(c("pattern", SENTENCE, "not found in", mcmc_out_file, "! Exiting ......")), fill=T)
	}
}


